.\" Manpage for renzoku.
.\" Contact renzoku@frostyfrog.net.in to correct errors or typos.
.TH man 1 "04 October 2015" "0.1.1" "renzoku man page"
.SH NAME
renzoku \- perform tedious tasks when files change
.SH SYNOPSIS
renzoku [OPTIONS] [DIRECTORY]
.SH DESCRIPTION
renzoku is a high level file watcher that performs user specified commands (via
renzoku.conf(5)) when underlying files change.
.SH OPTIONS
Renzoku does not currently take any options. That is a future feature.
.SH SEE ALSO
renzoku.conf(5), inotify(7)
.SH BUGS
A fair few known bugs. renzoku is still in early development afterall.
.SH AUTHOR
Colton Wolkins (frostyfrog2@gmail.com)
