language: cpp

compiler:
  - gcc
  - clang

#before_install:
#  - echo $LANG
#  - echo $LC_ALL
#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
#  - rvm use $RVM --install --binary --fuzzy
#  - gem update --system
#  - gem --version
#
#before_script:
#  - travis_retry bundle
#  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure --llvm-config /usr/local/opt/llvm/bin/llvm-config; fi

script: make test && make testv

#after_success:
#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master

notifications:
  email: true
#  irc:
#    channels:
#      - "chat.freenode.net#rubinius"
#    template:
#      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
#    on_success: change
#    on_failure: always
#    on_start: always

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
  - TRAVIS=true
os:
  - linux
  # - osx

osx_image: xcode61

