Document: renzoku
Title: Debian renzoku Manual
Author: <insert document author here>
Abstract: This manual describes what renzoku is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/renzoku/renzoku.sgml.gz

Format: postscript
Files: /usr/share/doc/renzoku/renzoku.ps.gz

Format: text
Files: /usr/share/doc/renzoku/renzoku.text.gz

Format: HTML
Index: /usr/share/doc/renzoku/html/index.html
Files: /usr/share/doc/renzoku/html/*.html
